# Generated by Django 6.0.6 on 2026-07-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitetoken',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
