# Generated by Django 6.0.6 on 2026-07-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_invitetoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitetoken',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
