# Generated by Django 6.0.6 on 2026-07-21 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_invitetoken_employee_id_invitetoken_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitetoken',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.department'),
        ),
    ]
